'use strict';
const assert = require('node:assert/strict');
const pii = require("../../electron/pii.cjs");
const cfg = pii.parseConfig({ 'agent.pii.mode': 'redact', 'agent.pii.categories': 'email,phone' });
assert.deepEqual(cfg, { mode: 'redact', categories: ['email', 'phone'] });
const input = '联系 alice@example.com 或 13800138000；订单号 1234567890123 不应默认当银行卡。';
const found = pii.inspect(input, cfg);
assert.deepEqual(found.map((item) => item.category), ['email', 'phone']);
const redacted = pii.apply(input, cfg);
assert.equal(redacted.changed, true);
assert.match(redacted.text, /\[REDACTED_EMAIL\]/);
assert.match(redacted.text, /\[REDACTED_PHONE\]/);
assert.doesNotMatch(redacted.text, /alice@example\.com|13800138000/);
const off = pii.apply(input, pii.parseConfig({}));
assert.equal(off.changed, false);
assert.equal(off.text, input);
const idConfig = pii.parseConfig({ 'agent.pii.mode': 'redact', 'agent.pii.categories': 'national_id_cn' });
const id = pii.apply('证件号 11010519491231002X', idConfig);
assert.deepEqual(id.findings.map((item) => item.category), ['national_id_cn']);
assert.match(id.text, /\[REDACTED_NATIONAL_ID\]/);
const invalidId = pii.apply('伪造号 110105194912310021', idConfig);
assert.equal(invalidId.findings.length, 0);
assert.equal(invalidId.text, '伪造号 110105194912310021');
const ssnConfig = pii.parseConfig({ 'agent.pii.mode': 'redact', 'agent.pii.categories': 'ssn_us' });
assert.match(pii.apply('SSN 123-45-6789', ssnConfig).text, /\[REDACTED_SSN\]/);
assert.equal(pii.apply('SSN 000-12-3456', ssnConfig).findings.length, 0);
console.log('PII: PASS — opt-in detection, redaction, category filtering, default off');
