package local.codenode;

import org.junit.jupiter.api.Test;
import java.util.List;
import static org.junit.jupiter.api.Assertions.*;

class WorkflowModelTest {
    @Test void connectsNamedPortsAndReplacesSingleInputLink(){WorkflowModel model=new WorkflowModel();var a=model.addNode(0,0);var b=model.addNode(0,0);var c=model.addNode(0,0);var extra=model.addPort(b,false);assertTrue(model.connect(a,a.outputs.getFirst(),b,extra));assertTrue(model.connect(c,c.outputs.getFirst(),b,extra));assertEquals(1,model.edges().size());assertEquals(c.id,model.edges().getFirst().source());assertEquals(extra.id,model.edges().getFirst().targetPort());}
    @Test void removingPortAlsoRemovesItsLinks(){WorkflowModel model=new WorkflowModel();var a=model.addNode(0,0);var b=model.addNode(0,0);var output=model.addPort(a,true);model.connect(a,output,b,b.inputs.getFirst());model.removePort(a,output,true);assertTrue(model.edges().isEmpty());}
    @Test void duplicatePreservesEditablePortDefinitions(){WorkflowModel model=new WorkflowModel();var source=model.addNode(0,0);source.inputs.getFirst().dataType="int";var copy=model.duplicate(source,20,20);assertEquals("int",copy.inputs.getFirst().dataType);assertNotSame(source.inputs.getFirst(),copy.inputs.getFirst());}
    @Test void anyInputAdoptsConnectedOutputType(){WorkflowModel model=new WorkflowModel();var source=model.addNode(0,0);var target=model.addNode(0,0);source.outputs.getFirst().dataType="文件夹";model.connect(source,target);assertEquals("文件夹",target.inputs.getFirst().dataType);}
    @Test void inferredInputReturnsToDeclaredTypeAfterDisconnect(){WorkflowModel model=new WorkflowModel();var source=model.addNode(0,0);var target=model.addNode(0,0);source.outputs.getFirst().declaredType="string";source.outputs.getFirst().dataType="string";model.connect(source,target);assertEquals("string",target.inputs.getFirst().dataType);model.removeEdges(List.copyOf(model.edges()));assertEquals("any",target.inputs.getFirst().dataType);}
    @Test void rejectsInvalidConnectionsWithReasonWithoutReplacingExistingInput(){WorkflowModel model=new WorkflowModel();var valid=model.addNode(0,0);var invalid=model.addNode(0,0);var target=model.addNode(0,0);valid.outputs.getFirst().declaredType="int";valid.outputs.getFirst().dataType="int";invalid.outputs.getFirst().declaredType="string";invalid.outputs.getFirst().dataType="string";target.inputs.getFirst().declaredType="number";target.inputs.getFirst().dataType="number";assertTrue(model.connectChecked(valid,valid.outputs.getFirst(),target,target.inputs.getFirst()).connected());WorkflowModel.ConnectionResult rejected=model.connectChecked(invalid,invalid.outputs.getFirst(),target,target.inputs.getFirst());assertFalse(rejected.connected());assertTrue(rejected.reason().contains("类型不兼容"));assertEquals(1,model.edges().size());assertEquals(valid.id,model.edges().getFirst().source());WorkflowModel.ConnectionResult self=model.connectChecked(valid,valid.outputs.getFirst(),valid,valid.inputs.getFirst());assertFalse(self.connected());assertTrue(self.reason().contains("节点自身"));}
    @Test void deepCopyKeepsReroutesIndependent(){WorkflowModel model=new WorkflowModel();var source=model.addNode(0,0);var target=model.addNode(300,0);model.connect(source,target);model.addReroute(model.edges().getFirst(),150,40);WorkflowModel copy=model.deepCopy();copy.edges().getFirst().reroutes().getFirst().y=90;assertEquals(40,model.edges().getFirst().reroutes().getFirst().y);assertEquals(90,copy.edges().getFirst().reroutes().getFirst().y);}
    @Test void deepCopyPreservesSharedRerouteIdentity(){WorkflowModel model=new WorkflowModel();var source=model.addNode(0,0);var first=model.addNode(300,0);var second=model.addNode(300,200);model.connect(source,first);var shared=model.addReroute(model.edges().getFirst(),150,50);model.connect(source,second);model.edges().getLast().reroutes().add(shared);WorkflowModel copy=model.deepCopy();assertSame(copy.edges().getFirst().reroutes().getFirst(),copy.edges().getLast().reroutes().getFirst());}
    @Test void groupOutputOnlyIncludesConnectedNonMutedUpstreamNodes(){WorkflowModel model=new WorkflowModel();var source=model.addNode(0,0);var middle=model.addNode(100,0);var empty=model.addNode(100,200);var output=model.addGroupOutput(300,0,"主程序输出");model.connect(source,middle);model.connect(middle,middle.outputs.getFirst(),output,output.inputs.getFirst());empty.muted=true;assertTrue(model.isValidGroupOutput(output));assertEquals(List.of(middle.id,source.id),model.upstreamOf(output).stream().map(n->n.id).toList());assertFalse(model.upstreamOf(output).contains(empty));}
    @Test void unconnectedGroupOutputIsInvalid(){WorkflowModel model=new WorkflowModel();var output=model.addGroupOutput(0,0,"空输出");assertFalse(model.isValidGroupOutput(output));assertTrue(model.upstreamOf(output).isEmpty());}
}
