package local.codenode;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.util.*;

public final class ProcessRequest {
    public static void main(String[] args) throws Exception {
        Path projectRoot = Path.of(System.getProperty("user.home")).resolve("Desktop").resolve("codenode-test-project");
        Path stateRoot = projectRoot.resolve(".codenode");

        Path inbox = stateRoot.resolve("queue/inbox");
        Path processing = stateRoot.resolve("queue/processing");
        Path results = stateRoot.resolve("results");

        String requestId = null;
        try (var dirs = Files.list(inbox)) {
            for (Path dir : dirs.filter(Files::isDirectory).toList()) {
                requestId = dir.getFileName().toString();
                break;
            }
        }
        if (requestId == null) { System.out.println("No pending requests"); return; }

        Path requestDir = inbox.resolve(requestId);
        Path processingDir = processing.resolve(requestId);
        try { Files.move(requestDir, processingDir, StandardCopyOption.ATOMIC_MOVE); }
        catch (AtomicMoveNotSupportedException e) { Files.move(requestDir, processingDir); }
        System.out.println("[1] Moved to processing: " + requestId);

        Map<String,Object> request = Json.object(Files.readString(processingDir.resolve("request.json")));
        System.out.println("[2] Read request: " + request.get("action") + " / " + request.get("language"));

        String code = """
# CodeNodeExport - HelloWorld
# Generated by CodeNode Stage 2

$desktop = [Environment]::GetFolderPath("Desktop")
$folderPath = Join-Path $desktop "CodeNodeExport"

# Node: 新建文件夹在桌面
Write-Output "Creating folder: $folderPath"
if (-not (Test-Path $folderPath)) {
    New-Item -Path $folderPath -ItemType Directory -Force | Out-Null
    Write-Output "Folder created successfully."
} else {
    Write-Output "Folder already exists."
}

# Node: 新建Word文档并写入HelloWorld
$docPath = Join-Path $folderPath "HelloWorld.md"

$content = @"
# Hello World!

Hello world!

---
Generated by CodeNode Desktop
"@

Set-Content -Path $docPath -Value $content -Encoding UTF8
Write-Output "Document created: $docPath"
Write-Output "Content written: Hello world!"

return @{
    FolderPath = $folderPath
    DocPath = $docPath
    Status = "Success"
}
""";

        @SuppressWarnings("unchecked")
        Map<String,Object> targetMap = (Map<String,Object>)request.get("target");
        @SuppressWarnings("unchecked")
        List<String> slotIds = (List<String>)targetMap.get("codeSlotIds");
        @SuppressWarnings("unchecked")
        Map<String,Object> baseRevisions = (Map<String,Object>)targetMap.get("baseSlotRevisions");

        List<Map<String,Object>> slotResults = new ArrayList<>();
        for (String slotId : slotIds) {
            long baseRev = baseRevisions.containsKey(slotId)
                    ? ((Number)baseRevisions.get(slotId)).longValue() : 0;
            slotResults.add(Map.of(
                    "slotId", slotId,
                    "baseRevision", baseRev,
                    "code", code,
                    "classificationKey", "agent.custom",
                    "language", "powershell",
                    "summary", "PowerShell script: creates CodeNodeExport folder on Desktop, writes HelloWorld.md with 'Hello world!' content"
            ));
        }

        Map<String,Object> result = new LinkedHashMap<>();
        result.put("schemaVersion", "4.0");
        result.put("requestId", requestId);
        result.put("mode", "markdown-blueprint");
        result.put("action", "build-markdown");
        result.put("status", "succeeded");
        result.put("summary", "Generated PowerShell script for creating folder and document on desktop");
        result.put("codeSlotResults", slotResults);
        result.put("diagnostics", List.of());
        result.put("processedAt", java.time.Instant.now().toString());

        Path resultDir = results.resolve(requestId);
        Files.createDirectories(resultDir);
        Path target = resultDir.resolve("result.json");
        Path temp = resultDir.resolve("result.json.tmp");
        Files.writeString(temp, Json.stringify(result), StandardCharsets.UTF_8,
                StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING);
        try { Files.move(temp, target, StandardCopyOption.REPLACE_EXISTING, StandardCopyOption.ATOMIC_MOVE); }
        catch (AtomicMoveNotSupportedException e) { Files.move(temp, target, StandardCopyOption.REPLACE_EXISTING); }

        System.out.println("[3] Result written: " + target);
        System.out.println("[4] Code slots updated: " + slotIds);
        System.out.println("\n=== Generated Code ===");
        System.out.println(code);

        // Move to completed
        Path completedDir = stateRoot.resolve("queue/completed").resolve(requestId);
        try { Files.move(processingDir, completedDir, StandardCopyOption.ATOMIC_MOVE); }
        catch (AtomicMoveNotSupportedException e) { Files.move(processingDir, completedDir); }
        System.out.println("\n[5] Request completed.");

        System.out.println("\nLaunch app to accept:");
        System.out.println("  java -jar target/codenode-desktop.jar " + projectRoot.resolve("HelloWorld.cnode"));
    }
}
