import { useEffect, useMemo, useState } from 'react';
import { useProjectStore } from '../../store/projectStore';
import { useGoalControlStore } from '../../store/goalControlStore';
import { useUiStore } from '../../store/uiStore';

const statusLabel:Record<string,string>={active:'进行中',paused:'已暂停',stopped:'已停止',completed:'已完成',archived:'已归档',todo:'待办',ready:'可运行',in_progress:'执行中',waiting:'等待',blocked:'阻塞',failed:'失败',cancelled:'已取消',unknown:'结果未知'};
export default function GoalControlPanel(){
  const root=useProjectStore(s=>s.root);const goals=useGoalControlStore(s=>s.goals);const selectedGoalId=useGoalControlStore(s=>s.selectedGoalId);const selectedTaskId=useGoalControlStore(s=>s.selectedTaskId);const select=useGoalControlStore(s=>s.select);const refresh=useGoalControlStore(s=>s.refresh);const storeError=useGoalControlStore(s=>s.error);
  const [title,setTitle]=useState('');const [objective,setObjective]=useState('');const [goalScope,setGoalScope]=useState('');const [goalExclusions,setGoalExclusions]=useState('');const [criteriaText,setCriteriaText]=useState('');const [maxTokens,setMaxTokens]=useState('');const [maxCostUsd,setMaxCostUsd]=useState('');const [taskTitle,setTaskTitle]=useState('');const [taskObjective,setTaskObjective]=useState('');const [taskReadScope,setTaskReadScope]=useState('');const [taskWriteScope,setTaskWriteScope]=useState('');const [taskDependencies,setTaskDependencies]=useState<string[]>([]);const [decisionQuestion,setDecisionQuestion]=useState('');const [decisionOptions,setDecisionOptions]=useState('');const [answer,setAnswer]=useState('');const [contextText,setContextText]=useState('');const [contextKind,setContextKind]=useState<'rules'|'taskMaterial'|'confirmedExperience'>('rules');const [waitKind,setWaitKind]=useState<'external_status'|'time'|'user_input'|'other'>('external_status');const [waitDescription,setWaitDescription]=useState('');const [waitExpected,setWaitExpected]=useState('');const [waitNextCheckAt,setWaitNextCheckAt]=useState('');const [verifyCommand,setVerifyCommand]=useState('');const [verifyCriterion,setVerifyCriterion]=useState('');const [gate,setGate]=useState<any>(null);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
  const goal=goals.find(g=>g.id===selectedGoalId)||null;const task=goal?.tasks.find(t=>t.id===selectedTaskId)||null;
  const api=window.codenode;
  const invoke=async(action:()=>Promise<any>,success='已保存')=>{if(!root||!api)return;setBusy(true);setMessage('');try{const result=await action();if(useProjectStore.getState().root!==root)return;if(!result?.ok)throw new Error(result?.error||'操作失败');setMessage(success);await refresh(root);}catch(error){if(useProjectStore.getState().root===root)setMessage(error instanceof Error?error.message:String(error));}finally{setBusy(false);}};
  const focusQueue=goals.flatMap(g=>[
    ...(g.decisions||[]).filter((d:any)=>d.status==='open').map((d:any)=>({goal:g,kind:'decision',id:d.id,taskId:d.taskIds?.[0]||null,label:'待决定 · '+d.question})),
    ...(g.tasks||[]).filter((t:any)=>['blocked','failed','waiting'].includes(t.status)||t.executionStatus==='unknown').map((t:any)=>({goal:g,kind:'task',id:t.id,taskId:t.id,label:(t.executionStatus==='unknown'?'结果未知 · ':t.status==='waiting'&&t.waitDue?'到检查时间 · ':`${statusLabel[t.status]||t.status} · `)+t.title})),
    ...(g.budget?.maxCostUsd!=null&&g.budget?.costBudgetUnknown?[{goal:g,kind:'budget',id:g.id,taskId:null,label:'费用未知，需复核预算'}]:[]),
  ]);
  useEffect(()=>{void refresh(root);},[root,refresh]);
  useEffect(()=>{setGate(null);setMessage('');},[selectedGoalId,selectedTaskId]);
  useEffect(()=>{if(!goal)return;setObjective(goal.objective||'');setGoalScope(goal.scope||'');setGoalExclusions(goal.exclusions||'');setCriteriaText((goal.criteria||[]).map((c:any)=>c.text).join('\n'));setMaxTokens(goal.budget?.maxTokens==null?'':String(goal.budget.maxTokens));setMaxCostUsd(goal.budget?.maxCostUsd==null?'':String(goal.budget.maxCostUsd));},[goal?.id,goal?.criteriaRevision]);
  const createGoal=()=>void invoke(()=>api!.goalCreate(root,{title,objective:objective||title,scope:goalScope,exclusions:goalExclusions,criteria:criteriaText.split(/\r?\n/).map(x=>x.trim()).filter(Boolean),maxTokens:maxTokens?Number(maxTokens):undefined,maxCostUsd:maxCostUsd?Number(maxCostUsd):undefined}).then(r=>{if(r.ok&&r.value?.id)select(r.value.id,null);return r;}),'Goal 已保存');
  const updateGoalDetails=()=>{if(!goal)return;void invoke(()=>api!.goalUpdate(root,goal.id,{objective,scope:goalScope,exclusions:goalExclusions}),'目标范围已保存');};
  const updateGoalCriteria=()=>{if(!goal)return;const rows=criteriaText.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);const criteria=rows.map((text,index)=>({id:goal.criteria[index]?.id,text,required:true}));void invoke(()=>api!.goalUpdate(root,goal.id,{criteria}),'验收条件已修订，旧证据已失效');};
  const updateGoalBudget=()=>{if(!goal)return;void invoke(()=>api!.goalUpdate(root,goal.id,{maxTokens:maxTokens?Number(maxTokens):null,maxCostUsd:maxCostUsd?Number(maxCostUsd):null}),'Goal 预算已保存');};
  const createTask=()=>{if(!goal)return;void invoke(()=>api!.goalTaskCreate(root,goal.id,{title:taskTitle,objective:taskObjective||taskTitle,readScope:taskReadScope.split(',').map(x=>x.trim()).filter(Boolean),writeScope:taskWriteScope.split(',').map(x=>x.trim()).filter(Boolean),dependsOn:taskDependencies,criteriaIds:goal.criteria.filter(c=>c.required).map(c=>c.id)}).then(r=>{if(r.ok&&r.value?.id){select(goal.id,r.value.id);setTaskTitle('');setTaskObjective('');setTaskReadScope('');setTaskWriteScope('');setTaskDependencies([]);}return r;}),'Task 已保存');};
  const canRun=()=>{if(!goal||!task)return;void invoke(()=>api!.goalCanRun(root,goal.id,task.id).then(r=>{if(r.ok)setGate(r.value);return r;}),'已更新运行资格');};
  const requeueTask=()=>{if(!goal||!task)return;void invoke(()=>api!.goalTaskUpdate(root,goal.id,task.id,{status:'todo'}),'Task 已重新排队');};
  const setWaiting=()=>{if(!goal||!task||!waitDescription.trim())return;void invoke(()=>api!.goalTaskUpdate(root,goal.id,task.id,{waitCondition:{kind:waitKind,description:waitDescription,expected:waitExpected,nextCheckAt:waitNextCheckAt?new Date(waitNextCheckAt).toISOString():null}}),'等待条件已保存');};
  const observeWait=(matched:boolean)=>{if(!goal||!task?.waitCondition)return;const id=`${task.id}:${task.updatedAt}:${matched?'matched':'pending'}`;void invoke(()=>api!.goalWaitObserve(root,goal.id,task.id,{id,source:'user-observation',status:waitExpected||task.waitCondition.expected||task.waitCondition.description,matched,revision:String(goal.criteriaRevision)}),matched?'条件已满足，Task 可运行':'等待状态已记录');};
  const createDecision=()=>{if(!goal)return;void invoke(()=>api!.goalDecisionCreate(root,goal.id,{question:decisionQuestion,options:decisionOptions.split(/\r?\n/).map(x=>x.trim()).filter(Boolean),taskIds:task?[task.id]:[]}).then(r=>{if(r.ok){setDecisionQuestion('');setDecisionOptions('');}return r;}),'业务决定已持久化');};
  const resolveDecision=(decisionId:string)=>{if(!goal)return;void invoke(()=>api!.goalDecisionResolve(root,decisionId,answer).then(r=>{if(r.ok)setAnswer('');return r;}),'决定已记录');};
  const addContext=()=>{if(!goal)return;void invoke(()=>api!.goalContextAdd(root,goal.id,contextKind,{content:contextText,source:'goal-panel',confirmed:contextKind!=='confirmedExperience'}).then(r=>{if(r.ok)setContextText('');return r;}),'项目上下文已保存');};
  const confirmExperience=(itemId:string)=>{if(!goal)return;void invoke(()=>api!.goalExperienceConfirm(root,goal.id,itemId),'经验已确认并可用于后续实现');};
  const verify=()=>{if(!goal||!verifyCommand.trim())return;void invoke(()=>api!.goalVerify(root,goal.id,task?.id||null,verifyCriterion||null,verifyCommand).then(r=>{if(!r.ok)throw new Error(r.error||'验收未通过');setGate({decision:'evidence',reason:'验收命令通过',runId:r.runId});return{ok:true};}),'验收证据已记录');};
  const setGoalStatus=(status:string)=>{if(!goal)return;void invoke(()=>api!.goalUpdate(root,goal.id,{status,...(status==='stopped'?{stopReason:'用户在 Goal 面板主动停止'}:{})}),'Goal 状态已更新');};
  const criterionOptions=useMemo(()=>goal?.criteria||[],[goal]);
  return <details className="goal-control-panel">
    <summary>长期目标与验收{goal?` · ${goal.title}`:''}</summary>
    <div className="goal-control-body">
      {!root&&<p className="settings-scope">先打开项目，Goal 与任务会保存在该项目中。</p>}
      {root&&<>
        {focusQueue.length>0&&<details className="goal-focus-queue"><summary>待处理事项 · {focusQueue.length}</summary>{focusQueue.map(item=><button key={item.kind+item.id} disabled={busy} onClick={()=>select(item.goal.id,item.taskId)}>{item.goal.title} · {item.label}</button>)}</details>}
        <div className="goal-toolbar"><select aria-label="项目 Goal" value={goal?.id||''} disabled={busy||!goals.length} onChange={e=>select(e.target.value||null,null)}><option value="">选择 Goal</option>{goals.map(g=><option key={g.id} value={g.id}>{g.title} · {statusLabel[g.status]||g.status}</option>)}</select><button onClick={()=>void refresh(root)} disabled={busy}>刷新</button></div>
        {!goal&&<div className="goal-form"><input aria-label="Goal 标题" value={title} onChange={e=>setTitle(e.target.value)} placeholder="目标标题"/><textarea aria-label="Goal 目标" value={objective} onChange={e=>setObjective(e.target.value)} placeholder="可审阅的目标与交付" rows={2}/><textarea aria-label="Goal 范围" value={goalScope} onChange={e=>setGoalScope(e.target.value)} placeholder="包含的项目范围" rows={2}/><textarea aria-label="Goal 排除项" value={goalExclusions} onChange={e=>setGoalExclusions(e.target.value)} placeholder="明确排除项" rows={2}/><textarea aria-label="验收条件" value={criteriaText} onChange={e=>setCriteriaText(e.target.value)} placeholder="必需验收条件，每行一项" rows={3}/><input aria-label="Goal Token 预算" type="number" min="1" value={maxTokens} onChange={e=>setMaxTokens(e.target.value)} placeholder="可选 Token 总预算"/><input aria-label="Goal 费用预算 USD" type="number" min="0" step="0.01" value={maxCostUsd} onChange={e=>setMaxCostUsd(e.target.value)} placeholder="可选 USD 预算"/><button disabled={busy||!title.trim()} onClick={createGoal}>创建 Goal</button></div>}
        {goal&&<>
          <div className="goal-summary"><strong>{goal.title}</strong><span>{statusLabel[goal.status]||goal.status}</span><p>{goal.objective}</p><small>验收版本 {goal.criteriaRevision} · 已用 token {goal.budget.usedTokens}{goal.budget.costUnknown?' · 外部费用未知':''}</small>
            <div className="goal-actions"><button disabled={busy||['completed','stopped','archived'].includes(goal.status)} onClick={()=>setGoalStatus(goal.status==='paused'?'active':'paused')}>{goal.status==='paused'?'恢复':'暂停'}</button><button disabled={busy||['completed','stopped','archived'].includes(goal.status)} onClick={()=>setGoalStatus('stopped')}>停止 Goal</button><button disabled={busy||!goal.qualified||['stopped','archived'].includes(goal.status)} onClick={()=>setGoalStatus('completed')}>完成验收</button>{['completed','stopped'].includes(goal.status)&&<button disabled={busy} onClick={()=>setGoalStatus('archived')}>归档</button>}</div>
          </div>
          <section><h4>目标范围与预算</h4><textarea aria-label="Goal 目标编辑" value={objective} onChange={e=>setObjective(e.target.value)} rows={2}/><textarea aria-label="Goal 范围编辑" value={goalScope} onChange={e=>setGoalScope(e.target.value)} placeholder="包含的项目范围" rows={2}/><textarea aria-label="Goal 排除项编辑" value={goalExclusions} onChange={e=>setGoalExclusions(e.target.value)} placeholder="明确排除项" rows={2}/><button disabled={busy||!objective.trim()} onClick={updateGoalDetails}>保存目标与范围</button><input aria-label="Goal Token 预算编辑" type="number" min="1" value={maxTokens} onChange={e=>setMaxTokens(e.target.value)} placeholder="不设 Token 上限"/><input aria-label="Goal 费用预算 USD 编辑" type="number" min="0" step="0.01" value={maxCostUsd} onChange={e=>setMaxCostUsd(e.target.value)} placeholder="不设 USD 上限"/><button disabled={busy} onClick={updateGoalBudget}>保存预算</button><small>费用未知时仅作记录，不会伪装成硬费用上限。</small></section>
          <section><h4>验收条件与当前证据</h4>{goal.criteria.map(c=><div className="goal-item" key={c.id}><span>{c.required?'必需':'可选'} · {c.text}</span><small>{goal.evidence.filter(e=>e.criterionId===c.id).map(e=>`${e.status}/${e.freshness?.valid?'有效':e.freshness?.reason||'待核验'}`).join('；')||'尚无证据'}</small></div>)}<textarea aria-label="验收条件编辑" value={criteriaText} onChange={e=>setCriteriaText(e.target.value)} placeholder="必需验收条件，每行一项；修订后旧证据失效" rows={3}/><button disabled={busy||!criteriaText.trim()} onClick={updateGoalCriteria}>修订验收条件</button></section>
          <section><h4>Task</h4>{goal.tasks.map(t=><button className="goal-task" aria-pressed={selectedTaskId===t.id} key={t.id} onClick={()=>select(goal.id,t.id)}>{statusLabel[t.status]||t.status} · {t.title}</button>)}
            <div className="goal-form"><input aria-label="Task 标题" value={taskTitle} onChange={e=>setTaskTitle(e.target.value)} placeholder="新增有界任务"/><textarea aria-label="Task 目标" value={taskObjective} onChange={e=>setTaskObjective(e.target.value)} placeholder="任务目标与排除项" rows={2}/><input aria-label="Task 读取范围" value={taskReadScope} onChange={e=>setTaskReadScope(e.target.value)} placeholder="读取路径/目录，逗号分隔（上下文约束）"/><input aria-label="Task 写入范围" value={taskWriteScope} onChange={e=>setTaskWriteScope(e.target.value)} placeholder="申明写入范围，相对目录/路径，逗号分隔"/><select aria-label="Task 依赖" multiple value={taskDependencies} onChange={e=>setTaskDependencies([...e.target.selectedOptions].map(option=>option.value))}>{goal.tasks.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select><button disabled={busy||!taskTitle.trim()} onClick={createTask}>新增 Task</button></div>
            {task&&<div className="goal-task-detail"><strong>当前 Task：{task.title}</strong><small>读取范围：{task.readScope.join(', ')||'未声明'} · 核对写入范围：{task.writeScope.join(', ')||'未限制'}</small>{task.writeScope.length>0&&<small>运行后核对越界修改；越界时任务判失败，修改保留供审阅。</small>}{task.executionStatus==='unknown'&&<small role="alert">上次应用关闭时尚未结算。请先检查该 Run 的文件差异和外部副作用，再选择重新排队。</small>}<button disabled={busy} onClick={canRun}>检查运行资格</button>{['blocked','failed','cancelled'].includes(task.status)&&<button disabled={busy} onClick={requeueTask}>复核后重新排队</button>}<button disabled={busy} onClick={()=>select(goal.id,null)}>取消任务绑定</button>{gate&&<p role="status">{gate.decision} · {gate.reason}</p>}
              {task.waitCondition&&<div className="goal-wait-condition"><small>等待：{task.waitCondition.description} · 预期：{task.waitCondition.expected||'未指定'}{task.waitCondition.nextCheckAt?` · 下次检查 ${task.waitCondition.nextCheckAt}`:''}{task.waitDue?' · 已到检查时间':''}</small>{task.status==='waiting'&&<><button disabled={busy} onClick={()=>observeWait(true)}>确认条件已满足</button><button disabled={busy} onClick={()=>observeWait(false)}>仍未满足（退避）</button></>}</div>}
              <div className="goal-form"><select aria-label="等待条件类型" value={waitKind} onChange={e=>setWaitKind(e.target.value as typeof waitKind)}><option value="external_status">外部状态</option><option value="time">时间</option><option value="user_input">用户输入</option><option value="other">其他</option></select><input aria-label="等待条件说明" value={waitDescription} onChange={e=>setWaitDescription(e.target.value)} placeholder="例如 CI 完成、审批返回或服务可用"/><input aria-label="预期状态" value={waitExpected} onChange={e=>setWaitExpected(e.target.value)} placeholder="预期值或状态"/><input aria-label="下次检查时间" type="datetime-local" value={waitNextCheckAt} onChange={e=>setWaitNextCheckAt(e.target.value)}/><button disabled={busy||!waitDescription.trim()} onClick={setWaiting}>设置等待</button></div>
            </div>}
          </section>
          <section><h4>业务决定</h4>{goal.decisions.map(d=><div className="goal-item" key={d.id}><span>{d.status==='open'?'待决定':'已决定'} · {d.question}</span>{d.status==='open'&&<><small>{d.taskIds.length?`阻塞 Task：${d.taskIds.join(', ')}`:'Goal 级决定'} · {d.options.join(' / ')}</small><div><input aria-label={'决定 '+d.question} value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="填写决定"/><button disabled={busy||!answer.trim()} onClick={()=>resolveDecision(d.id)}>保存决定</button></div></>}</div>)}<div className="goal-form"><input aria-label="决定问题" value={decisionQuestion} onChange={e=>setDecisionQuestion(e.target.value)} placeholder="需要持久化的问题"/><textarea aria-label="决定选项" value={decisionOptions} onChange={e=>setDecisionOptions(e.target.value)} placeholder="选项，每行一项" rows={2}/><button disabled={busy||!decisionQuestion.trim()} onClick={createDecision}>记录决定{task?'（仅阻塞当前 Task）':'（Goal 级）'}</button></div></section>
          <section><h4>项目规范、任务材料与经验</h4>{(['rules','taskMaterial','confirmedExperience'] as const).flatMap(kind=>(goal.context?.[kind]||[]).map((item:any)=><div className="goal-item" key={item.id}><span>{kind==='rules'?'项目规范':kind==='taskMaterial'?'任务材料':item.confirmed?'已确认经验':item.generated?'待复核经验（自动建议）':'待复核经验'} · {item.content}</span><small>来源：{item.source||'user'} · 修订 {item.revision}</small>{kind==='confirmedExperience'&&!item.confirmed&&<button disabled={busy} onClick={()=>confirmExperience(item.id)}>确认写入项目经验</button>}</div>))}<select aria-label="上下文类别" value={contextKind} onChange={e=>setContextKind(e.target.value as typeof contextKind)}><option value="rules">项目规范</option><option value="taskMaterial">任务材料</option><option value="confirmedExperience">经验候选（需人工确认）</option></select><textarea aria-label="上下文内容" value={contextText} onChange={e=>setContextText(e.target.value)} placeholder="记录可追溯的规范、任务材料或经验候选" rows={2}/><button disabled={busy||!contextText.trim()} onClick={addContext}>保存上下文</button></section>
          <section><h4>独立验收</h4><select aria-label="关联验收条件" value={verifyCriterion} onChange={e=>setVerifyCriterion(e.target.value)}><option value="">选择 Goal 条件</option>{criterionOptions.map(c=><option key={c.id} value={c.id}>{c.text}</option>)}</select><input aria-label="验收命令" value={verifyCommand} onChange={e=>setVerifyCommand(e.target.value)} placeholder="例如 npm test（运行前会逐次审批）"/><button disabled={busy||!verifyCommand.trim()} onClick={verify}>运行并记录证据</button></section>
        </>}
      </>}
      {(storeError||message)&&<p role="status" className="settings-scope">{message||storeError}</p>}
    </div>
  </details>;
}
