import { useEffect, useMemo, useState } from 'react';
import { useProjectStore } from '../../store/projectStore';
import { useGoalControlStore } from '../../store/goalControlStore';
import { useUiStore } from '../../store/uiStore';

const statusLabel:Record<string,string>={active:'进行中',paused:'已暂停',stopped:'已停止',completed:'已完成',archived:'已归档',todo:'待办',ready:'可运行',in_progress:'执行中',waiting:'等待',blocked:'阻塞',failed:'失败',cancelled:'已取消'};
export default function GoalControlPanel(){
  const root=useProjectStore(s=>s.root);const goals=useGoalControlStore(s=>s.goals);const selectedGoalId=useGoalControlStore(s=>s.selectedGoalId);const selectedTaskId=useGoalControlStore(s=>s.selectedTaskId);const select=useGoalControlStore(s=>s.select);const refresh=useGoalControlStore(s=>s.refresh);const storeError=useGoalControlStore(s=>s.error);
  const [title,setTitle]=useState('');const [objective,setObjective]=useState('');const [criteriaText,setCriteriaText]=useState('');const [taskTitle,setTaskTitle]=useState('');const [taskObjective,setTaskObjective]=useState('');const [taskWriteScope,setTaskWriteScope]=useState('');const [decisionQuestion,setDecisionQuestion]=useState('');const [decisionOptions,setDecisionOptions]=useState('');const [answer,setAnswer]=useState('');const [contextText,setContextText]=useState('');const [contextKind,setContextKind]=useState<'rules'|'taskMaterial'|'confirmedExperience'>('rules');const [verifyCommand,setVerifyCommand]=useState('');const [verifyCriterion,setVerifyCriterion]=useState('');const [gate,setGate]=useState<any>(null);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
  const goal=goals.find(g=>g.id===selectedGoalId)||null;const task=goal?.tasks.find(t=>t.id===selectedTaskId)||null;
  const api=window.codenode;
  const invoke=async(action:()=>Promise<any>,success='已保存')=>{if(!root||!api)return;setBusy(true);setMessage('');try{const result=await action();if(useProjectStore.getState().root!==root)return;if(!result?.ok)throw new Error(result?.error||'操作失败');setMessage(success);await refresh(root);}catch(error){if(useProjectStore.getState().root===root)setMessage(error instanceof Error?error.message:String(error));}finally{setBusy(false);}};
  useEffect(()=>{void refresh(root);},[root,refresh]);
  useEffect(()=>{setGate(null);setMessage('');},[selectedGoalId,selectedTaskId]);
  const createGoal=()=>void invoke(()=>api!.goalCreate(root,{title,objective:objective||title,criteria:criteriaText.split(/\r?\n/).map(x=>x.trim()).filter(Boolean)}).then(r=>{if(r.ok&&r.value?.id)select(r.value.id,null);return r;}),'Goal 已保存');
  const createTask=()=>{if(!goal)return;void invoke(()=>api!.goalTaskCreate(root,goal.id,{title:taskTitle,objective:taskObjective||taskTitle,writeScope:taskWriteScope.split(',').map(x=>x.trim()).filter(Boolean),criteriaIds:goal.criteria.filter(c=>c.required).map(c=>c.id)}).then(r=>{if(r.ok&&r.value?.id)select(goal.id,r.value.id);return r;}),'Task 已保存');};
  const canRun=()=>{if(!goal||!task)return;void invoke(()=>api!.goalCanRun(root,goal.id,task.id).then(r=>{if(r.ok)setGate(r.value);return r;}),'已更新运行资格');};
  const createDecision=()=>{if(!goal)return;void invoke(()=>api!.goalDecisionCreate(root,goal.id,{question:decisionQuestion,options:decisionOptions.split(/\r?\n/).map(x=>x.trim()).filter(Boolean),taskIds:task?[task.id]:[]}).then(r=>{if(r.ok){setDecisionQuestion('');setDecisionOptions('');}return r;}),'业务决定已持久化');};
  const resolveDecision=(decisionId:string)=>{if(!goal)return;void invoke(()=>api!.goalDecisionResolve(root,decisionId,answer).then(r=>{if(r.ok)setAnswer('');return r;}),'决定已记录');};
  const addContext=()=>{if(!goal)return;void invoke(()=>api!.goalContextAdd(root,goal.id,contextKind,{content:contextText,source:'goal-panel',confirmed:contextKind!=='confirmedExperience'}).then(r=>{if(r.ok)setContextText('');return r;}),'项目上下文已保存');};
  const verify=()=>{if(!goal||!verifyCommand.trim())return;void invoke(()=>api!.goalVerify(root,goal.id,task?.id||null,verifyCriterion||null,verifyCommand).then(r=>{if(!r.ok)throw new Error(r.error||'验收未通过');setGate({decision:'evidence',reason:'验收命令通过',runId:r.runId});return{ok:true};}),'验收证据已记录');};
  const setGoalStatus=(status:string)=>{if(!goal)return;void invoke(()=>api!.goalUpdate(root,goal.id,{status}),'Goal 状态已更新');};
  const criterionOptions=useMemo(()=>goal?.criteria||[],[goal]);
  return <details className="goal-control-panel">
    <summary>长期目标与验收{goal?` · ${goal.title}`:''}</summary>
    <div className="goal-control-body">
      {!root&&<p className="settings-scope">先打开项目，Goal 与任务会保存在该项目中。</p>}
      {root&&<>
        <div className="goal-toolbar"><select aria-label="项目 Goal" value={goal?.id||''} disabled={busy||!goals.length} onChange={e=>select(e.target.value||null,null)}><option value="">选择 Goal</option>{goals.map(g=><option key={g.id} value={g.id}>{g.title} · {statusLabel[g.status]||g.status}</option>)}</select><button onClick={()=>void refresh(root)} disabled={busy}>刷新</button></div>
        {!goal&&<div className="goal-form"><input aria-label="Goal 标题" value={title} onChange={e=>setTitle(e.target.value)} placeholder="目标标题"/><textarea aria-label="Goal 范围" value={objective} onChange={e=>setObjective(e.target.value)} placeholder="目标与范围" rows={2}/><textarea aria-label="验收条件" value={criteriaText} onChange={e=>setCriteriaText(e.target.value)} placeholder="验收条件，每行一项" rows={3}/><button disabled={busy||!title.trim()} onClick={createGoal}>创建 Goal</button></div>}
        {goal&&<>
          <div className="goal-summary"><strong>{goal.title}</strong><span>{statusLabel[goal.status]||goal.status}</span><p>{goal.objective}</p><small>验收版本 {goal.criteriaRevision} · 已用 token {goal.budget.usedTokens}{goal.budget.costUnknown?' · 外部费用未知':''}</small>
            <div className="goal-actions"><button disabled={busy} onClick={()=>setGoalStatus(goal.status==='paused'?'active':'paused')}>{goal.status==='paused'?'恢复':'暂停'}</button><button disabled={busy||goal.status==='completed'} onClick={()=>setGoalStatus('stopped')}>停止 Goal</button><button disabled={busy||!goal.complete} onClick={()=>setGoalStatus('completed')}>完成验收</button></div>
          </div>
          <section><h4>验收条件与当前证据</h4>{goal.criteria.map(c=><div className="goal-item" key={c.id}><span>{c.required?'必需':'可选'} · {c.text}</span><small>{goal.evidence.filter(e=>e.criterionId===c.id).map(e=>`${e.status}/${e.freshness?.valid?'有效':e.freshness?.reason||'待核验'}`).join('；')||'尚无证据'}</small></div>)}</section>
          <section><h4>Task</h4>{goal.tasks.map(t=><button className="goal-task" aria-pressed={selectedTaskId===t.id} key={t.id} onClick={()=>select(goal.id,t.id)}>{statusLabel[t.status]||t.status} · {t.title}</button>)}
            <div className="goal-form"><input aria-label="Task 标题" value={taskTitle} onChange={e=>setTaskTitle(e.target.value)} placeholder="新增有界任务"/><textarea aria-label="Task 目标" value={taskObjective} onChange={e=>setTaskObjective(e.target.value)} placeholder="任务目标与排除项" rows={2}/><input aria-label="Task 写入范围" value={taskWriteScope} onChange={e=>setTaskWriteScope(e.target.value)} placeholder="申明写入范围，相对目录/路径，逗号分隔"/><button disabled={busy||!taskTitle.trim()} onClick={createTask}>新增 Task</button></div>
            {task&&<div className="goal-task-detail"><strong>当前 Task：{task.title}</strong><small>读取范围：{task.readScope.join(', ')||'未声明'} · 核对写入范围：{task.writeScope.join(', ')||'未限制'}</small>{task.writeScope.length>0&&<small>运行后核对越界修改；越界时任务判失败，修改保留供审阅。</small>}<button disabled={busy} onClick={canRun}>检查运行资格</button><button disabled={busy} onClick={()=>select(goal.id,null)}>取消任务绑定</button>{gate&&<p role="status">{gate.decision} · {gate.reason}</p>}</div>}
          </section>
          <section><h4>业务决定</h4>{goal.decisions.map(d=><div className="goal-item" key={d.id}><span>{d.status==='open'?'待决定':'已决定'} · {d.question}</span>{d.status==='open'&&<><small>{d.taskIds.length?`阻塞 Task：${d.taskIds.join(', ')}`:'Goal 级决定'} · {d.options.join(' / ')}</small><div><input aria-label={'决定 '+d.question} value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="填写决定"/><button disabled={busy||!answer.trim()} onClick={()=>resolveDecision(d.id)}>保存决定</button></div></>}</div>)}<div className="goal-form"><input aria-label="决定问题" value={decisionQuestion} onChange={e=>setDecisionQuestion(e.target.value)} placeholder="需要持久化的问题"/><textarea aria-label="决定选项" value={decisionOptions} onChange={e=>setDecisionOptions(e.target.value)} placeholder="选项，每行一项" rows={2}/><button disabled={busy||!decisionQuestion.trim()} onClick={createDecision}>记录决定{task?'（仅阻塞当前 Task）':'（Goal 级）'}</button></div></section>
          <section><h4>项目规范、任务材料与经验</h4><select aria-label="上下文类别" value={contextKind} onChange={e=>setContextKind(e.target.value as typeof contextKind)}><option value="rules">项目规范</option><option value="taskMaterial">任务材料</option><option value="confirmedExperience">已确认经验</option></select><textarea aria-label="上下文内容" value={contextText} onChange={e=>setContextText(e.target.value)} placeholder="仅录入确认过且可追溯的内容" rows={2}/><button disabled={busy||!contextText.trim()} onClick={addContext}>保存上下文</button></section>
          <section><h4>独立验收</h4><select aria-label="关联验收条件" value={verifyCriterion} onChange={e=>setVerifyCriterion(e.target.value)}><option value="">选择 Goal 条件</option>{criterionOptions.map(c=><option key={c.id} value={c.id}>{c.text}</option>)}</select><input aria-label="验收命令" value={verifyCommand} onChange={e=>setVerifyCommand(e.target.value)} placeholder="例如 npm test（运行前会逐次审批）"/><button disabled={busy||!verifyCommand.trim()} onClick={verify}>运行并记录证据</button></section>
        </>}
      </>}
      {(storeError||message)&&<p role="status" className="settings-scope">{message||storeError}</p>}
    </div>
  </details>;
}
